### ISSUE TITLE
Apply to common MS Office formats

### ISSUE THREAD

**Issue by LachlanAndrew** [vonBarbarosa/pbit-git#9]
This is a brilliant idea.

This tool would receive a lot more support (to improve robustness, or integrate with mainline git) if it handled standard formats like .docx, .xlsx, .pptx .  I'll have a go if I get the time.

Do you have any tips about how to make this more portable?  That is, how can I make it easy for someone who clones the repo to have a seamless experience?

**Comment by vonBarbarosa** [comment]
Hello @LachlanAndrew , thanks for your kindness!

This repo is a fork from [ckrf/xlsx-git](https://github.com/ckrf/xlsx-git), which was primarily intended to work with XLSX files. There are a couple of forks of this primary repo, you can check the fork tree to see if you find something you can use.

I adapted it to my own purposes, and I stopped working with this repo. 

I'm afraid I have no tips for you besides what's already commited to [README.md](https://github.com/vonBarbarosa/pbit-git/blob/master/README.md) and [install-git-hooks.sh](https://github.com/vonBarbarosa/pbit-git/blob/master/install-git-hooks.sh)...

I'm closing this issue because I won't be working on that task, but feel free to comment or get in contact in any other way. Tnx!
